server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: restapi
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:shop
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

external-api:
  hnb-url: "https://api.hnb.hr/"

